ti5:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

    gravity_comp_controller:
      type: arm_controllers/GravityCompController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      gains:
        elfin_joint1:
          pid: {p: 10.0, i: 0.3, d: 0.1, i_clamp: 1, antiwindup: true}
        elfin_joint2: 
          pid: {p: 15.0, i: 0.3, d: 0.1, i_clamp: 1, antiwindup: true}
        elfin_joint3:
          pid: {p: 10.0, i: 0.0, d: 0.0, i_clamp: 1, antiwindup: true}
        elfin_joint4: 
          pid: {p: 10.0, i: 0.0, d: 0.0, i_clamp: 1, antiwindup: true}
        elfin_joint5: 
          pid: {p: 10.0, i: 0.0, d: 0.0, i_clamp: 1, antiwindup: true}
        elfin_joint6: 
          pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 1, antiwindup: true}
      root_link: world
      tip_link: elfin_link6